// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHuBnuRdmIZZdslanxp5bZCascvW0yz4c',
    appId: '1:259557209560:web:0e1915d49704f549666ead',
    messagingSenderId: '259557209560',
    projectId: 'flutter-personalnotes',
    authDomain: 'flutter-personalnotes.firebaseapp.com',
    storageBucket: 'flutter-personalnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHgGK4DvTQKjTTIEEyGSCBNLWYvEN97U',
    appId: '1:259557209560:android:afd2fedeb12fd392666ead',
    messagingSenderId: '259557209560',
    projectId: 'flutter-personalnotes',
    storageBucket: 'flutter-personalnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxR6SLX0lErV6pqNcZ9-OWX_gYMdoQGQ',
    appId: '1:259557209560:ios:fdbcaa2b10640d0b666ead',
    messagingSenderId: '259557209560',
    projectId: 'flutter-personalnotes',
    storageBucket: 'flutter-personalnotes.appspot.com',
    iosClientId: '259557209560-r944eg0t5k2eipdkk76p1clq3fkgp05o.apps.googleusercontent.com',
    iosBundleId: 'com.devluqman.personalnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxR6SLX0lErV6pqNcZ9-OWX_gYMdoQGQ',
    appId: '1:259557209560:ios:fdbcaa2b10640d0b666ead',
    messagingSenderId: '259557209560',
    projectId: 'flutter-personalnotes',
    storageBucket: 'flutter-personalnotes.appspot.com',
    iosClientId: '259557209560-r944eg0t5k2eipdkk76p1clq3fkgp05o.apps.googleusercontent.com',
    iosBundleId: 'com.devluqman.personalnotes',
  );
}
